### ISSUE TITLE
Some bad practices

### ISSUE THREAD

**Issue by johnnestebann** [stndc/codeskate#4]
Hello! First of all I want to congratulate you for the project you have developed. And I want to tell you that your project has some bad practices on how to do some things.
First, your index.php file is in the folder root, that is a problem because if your web server fail, all your source code is going to be expose to the client. It should be in a solo folder.
Second, it has the configurations in a php file, so if you are using multiple environments and a version control tool, you are going to commit the configurations on the repository, and that is somenthing we don't want. You should save the configuration on .env files which are not commited on the repository.
Third, you are not using composer, de best tool for autoloading php files (and php dependencies).
Fourth, you are deeply coupled to bootstrap as a css frontend client.
I hope this suggestions could help you to achieve a better tool.
Greetings!

**Comment by stndc** [comment]
Hello Esteban. Thank you very much for your words. One of the points to follow with this project was to work with composer. But I wanted to finish Skater before continuing. I'm going to follow your advice and also seriously thought about removing Bootstrap and leaving it clean.
Now I'm working on the second part of Skater but first I'm going to correct the bad practices.
Thank you very much again.
